name: promote_to_Prod
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: Image tag to deploy
        required: true

jobs:
  promote:
    environment: prod
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: |
          ACTIVE_COLOR=$(kubectl get svc color-app \
            -n prod \
            -o jsonpath='{.spec.selector.color}')
          if [ "$ACTIVE_COLOR" = "blue" ]; then
            TARGET_COLOR=green
          else
            TARGET_COLOR=blue
          fi
          kubectl set image deployment/color-app-${TARGET_COLOR} \
            color-app=hanihammadeh/web-app:${{github.event.inputs.image_tag}} \
            -n prod

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/color-app-${TARGET_COLOR} \
            -n prod
